config/routes.rb
Gothere::Application.routes.draw do


  post 'expedia' => 'expedia#search'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root to: 'home#index'

  # devise_for :users
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expedia_controller.rb
class ExpediaController < ApplicationController
  
  def search
    require "expedia"
    
    Expedia.cid = 55505
    Expedia.api_key = ENV['EXPEDIA_KEY']
    Expedia.shared_secret = ENV['EXPEDIA_SECRET']
    Expedia.currency_code = 'USD'
    Expedia.minor_rev = 13

    api = Expedia::Api.new

    response = api.get_list({city: params[:search], useGeoCoder: true, minTripAdvisorRating: 3.0})
    unless response.inspect.include? "APIError"
      render :json => response.body['HotelListResponse']['HotelList']['HotelSummary'].to_json
    else
      render :json => { error: true }
    end

  end

  def arc_map

  # Convert lat/lon (must be in radians) to Cartesian coordinates for each location.
  # X = cos(lat) * cos(lon)
  # Y = cos(lat) * sin(lon)
  # Z = sin(lat)

  # Compute average x, y and z coordinates.
  # x = (x1 + x2 + ... + xn) / n
  # y = (y1 + y2 + ... + yn) / n
  # z = (z1 + z2 + ... + zn) / n

  # Convert average x, y, z coordinate to latitude and longitude.
  # Lon = atan2(y, x)
  # Hyp = sqrt(x * x + y * y)
  # Lat = atan2(z, hyp)
    
  # @response.body['HotelListResponse']['HotelList']['HotelSummary']



  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expedia_helper.rb
module ExpediaHelper
end

app/views/expedia/new.html.erb
<h1>Expedia#new</h1>
<p>Find me in app/views/expedia/new.html.erb</p>

app/views/home/index.html.erb
<input type="checkbox" name="toggle-crime" data-size="mini", class="label-toggle-crime">
<label id="label-toggle-crime">Toggle Crime Map</label>
<br>
<!-- <input type="checkbox" name="toggle-supermarkets" data-size="mini", class="label-toggle-supermarkets">
<label id="label-toggle-supermarkets">Toggle SuperMarket Access Map</label>
 -->
<div id="content"
     data-dojo-type="dijit/layout/BorderContainer"
     data-dojo-props="design:'headline', gutters:true"
     style="width: 100%; height: 100%; margin: 0;">

  <div id="map"
       data-dojo-type="dijit/layout/ContentPane"
       data-dojo-props="region:'center'"
       style="overflow:hidden;">
  </div>

  <div data-dojo-type="dijit/layout/AccordionContainer">
    <div data-dojo-type="dijit/layout/ContentPane" id="legendPane"
         data-dojo-props="title:'Legend', selected:true">
      <div id="legendDiv"></div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar">
        </span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %> 
        <span class='glyphicon glyphicon-send'></span>
        Safe Travels
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>

      <%= form_tag expedia_path, :method => :post, class: "navbar-form navbar-right", id: 'form-search', role: "search" do %> 
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Which City?" %> 
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Home', root_path %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to "Sign up", new_user_registration_path %></li>
  <li><%= link_to "Login", new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GoThere" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Gothere" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <!--map-->
    <script src="http://js.arcgis.com/3.8/"></script>
    <link rel="stylesheet" href="http://js.arcgis.com/3.8/js/esri/css/esri.css">

    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <div class="slider slider-horizontal"></div>
          <ul class="nav nav-sidebar">
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>